### ISSUE TITLE
compose-specification not respected after node reboot

### ISSUE THREAD

**Issue by marcosdly** [aaraney/deployx#1] opened 2023-06-08 13:52 UTC
I started using `deployx` because regular `stack deploy` was trying to, at all costs, pull my locally built image from some registry, and it solved it be allowing me to use `pull_policy: never|missing` while doing a manual deploy. But, after a system reboot, when docker tries to pull the image again to restart the containers, it no longer is able to pull from local.

Here are the logs from `journalctl -u docker` since the reboot:
```
-- Boot d9ea720441cc4ce0a6813b42a09918d0 --
Jun 08 08:36:31 taken-departure systemd[1]: Starting docker.service - Docker Application Container Engine...
Jun 08 08:36:32 taken-departure dockerd[907]: time="2023-06-08T08:36:32.097734969-03:00" level=info msg="Starting up"
Jun 08 08:36:32 taken-departure dockerd[907]: time="2023-06-08T08:36:32.206269542-03:00" level=info msg="[core] parsed scheme: \"unix\"" module=grpc
Jun 08 08:36:32 taken-departure dockerd[907]: time="2023-06-08T08:36:32.206313079-03:00" level=info msg="[core] scheme \"unix\" not registered, fallback to default scheme" module=grpc
Jun 08 08:36:32 taken-departure dockerd[907]: time="2023-06-08T08:36:32.206372506-03:00" level=info msg="[core] ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
Jun 08 08:36:32 taken-departure dockerd[907]: time="2023-06-08T08:36:32.206400503-03:00" level=info msg="[core] ClientConn switching balancer to \"pick_first\"" module=grpc
Jun 08 08:36:32 taken-departure dockerd[907]: time="2023-06-08T08:36:32.206416566-03:00" level=info msg="[core] Channel switches to new LB policy \"pick_first\"" module=grpc
Jun 08 08:36:32 taken-departure dockerd[907]: time="2023-06-08T08:36:32.207759765-03:00" level=info msg="[core] Subchannel Connectivity change to CONNECTING" module=grpc
Jun 08 08:36:32 taken-departure dockerd[907]: time="2023-06-08T08:36:32.208355272-03:00" level=info msg="[core] Subchannel picks a new address \"unix:///run/containerd/containerd.sock\" to connect" module=grpc
Jun 08 08:36:32 taken-departure dockerd[907]: time="2023-06-08T08:36:32.208355629-03:00" level=info msg="[core] Channel Connectivity change to CONNECTING" module=grpc
Jun 08 08:36:32 taken-departure dockerd[907]: time="2023-06-08T08:36:32.209790089-03:00" level=info msg="[core] Subchannel Connectivity change to READY" module=grpc
Jun 08 08:36:32 taken-departure dockerd[907]: time="2023-06-08T08:36:32.209842804-03:00" level=info msg="[core] Channel Connectivity change to READY" module=grpc
Jun 08 08:36:32 taken-departure dockerd[907]: time="2023-06-08T08:36:32.211979406-03:00" level=info msg="[core] parsed scheme: \"unix\"" module=grpc
Jun 08 08:36:32 taken-departure dockerd[907]: time="2023-06-08T08:36:32.212004456-03:00" level=info msg="[core] scheme \"unix\" not registered, fallback to default scheme" module=grpc
Jun 08 08:36:32 taken-departure dockerd[907]: time="2023-06-08T08:36:32.212045496-03:00" level=info msg="[core] ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
Jun 08 08:36:32 taken-departure dockerd[907]: time="2023-06-08T08:36:32.212061088-03:00" level=info msg="[core] ClientConn switching balancer to \"pick_first\"" module=grpc
Jun 08 08:36:32 taken-departure dockerd[907]: time="2023-06-08T08:36:32.212071406-03:00" level=info msg="[core] Channel switches to new LB policy \"pick_first\"" module=grpc
Jun 08 08:36:32 taken-departure dockerd[907]: time="2023-06-08T08:36:32.212100554-03:00" level=info msg="[core] Subchannel Connectivity change to CONNECTING" module=grpc
Jun 08 08:36:32 taken-departure dockerd[907]: time="2023-06-08T08:36:32.212135911-03:00" level=info msg="[core] Subchannel picks a new address \"unix:///run/containerd/containerd.sock\" to connect" module=grpc
Jun 08 08:36:32 taken-departure dockerd[907]: time="2023-06-08T08:36:32.212200996-03:00" level=info msg="[core] Channel Connectivity change to CONNECTING" module=grpc
Jun 08 08:36:32 taken-departure dockerd[907]: time="2023-06-08T08:36:32.213049097-03:00" level=info msg="[core] Subchannel Connectivity change to READY" module=grpc
Jun 08 08:36:32 taken-departure dockerd[907]: time="2023-06-08T08:36:32.213087431-03:00" level=info msg="[core] Channel Connectivity change to READY" module=grpc
Jun 08 08:36:32 taken-departure dockerd[907]: time="2023-06-08T08:36:32.330181419-03:00" level=info msg="[graphdriver] using prior storage driver: overlay2"
Jun 08 08:36:32 taken-departure dockerd[907]: time="2023-06-08T08:36:32.448367962-03:00" level=info msg="Loading containers: start."
Jun 08 08:36:33 taken-departure dockerd[907]: time="2023-06-08T08:36:33.096175323-03:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Jun 08 08:36:33 taken-departure dockerd[907]: time="2023-06-08T08:36:33.212016338-03:00" level=info msg="Loading containers: done."
Jun 08 08:36:33 taken-departure dockerd[907]: time="2023-06-08T08:36:33.338398530-03:00" level=info msg="Docker daemon" commit=5d6db84 graphdriver(s)=overlay2 version=20.10.24+dfsg1
Jun 08 08:36:33 taken-departure dockerd[907]: time="2023-06-08T08:36:33.362942168-03:00" level=info msg="[core] parsed scheme: \"\"" module=grpc
Jun 08 08:36:33 taken-departure dockerd[907]: time="2023-06-08T08:36:33.364553058-03:00" level=info msg="[core] scheme \"\" not registered, fallback to default scheme" module=grpc
Jun 08 08:36:33 taken-departure dockerd[907]: time="2023-06-08T08:36:33.364594179-03:00" level=info msg="[core] ccResolverWrapper: sending update to cc: {[{/var/run/docker/swarm/control.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
Jun 08 08:36:33 taken-departure dockerd[907]: time="2023-06-08T08:36:33.364619994-03:00" level=info msg="[core] ClientConn switching balancer to \"pick_first\"" module=grpc
Jun 08 08:36:33 taken-departure dockerd[907]: time="2023-06-08T08:36:33.364639317-03:00" level=info msg="[core] Channel switches to new LB policy \"pick_first\"" module=grpc
Jun 08 08:36:33 taken-departure dockerd[907]: time="2023-06-08T08:36:33.364679279-03:00" level=info msg="[core] Subchannel Connectivity change to CONNECTING" module=grpc
Jun 08 08:36:33 taken-departure dockerd[907]: time="2023-06-08T08:36:33.364737425-03:00" level=info msg="[core] blockingPicker: the picked transport is not ready, loop back to repick" module=grpc
Jun 08 08:36:33 taken-departure dockerd[907]: time="2023-06-08T08:36:33.364760431-03:00" level=info msg="[core] Channel Connectivity change to CONNECTING" module=grpc
Jun 08 08:36:33 taken-departure dockerd[907]: time="2023-06-08T08:36:33.364777843-03:00" level=info msg="[core] Subchannel picks a new address \"/var/run/docker/swarm/control.sock\" to connect" module=grpc
Jun 08 08:36:33 taken-departure dockerd[907]: time="2023-06-08T08:36:33.369047207-03:00" level=info msg="Listening for connections" addr="[::]:2377" module=node node.id=0e3qrqn1hrskau5qzzm3c6c5j proto=tcp
Jun 08 08:36:33 taken-departure dockerd[907]: time="2023-06-08T08:36:33.369114446-03:00" level=info msg="Listening for local connections" addr=/var/run/docker/swarm/control.sock module=node node.id=0e3qrqn1hrskau5qzzm3c6c5j proto=unix
Jun 08 08:36:33 taken-departure dockerd[907]: time="2023-06-08T08:36:33.371222640-03:00" level=info msg="[core] Subchannel Connectivity change to READY" module=grpc
Jun 08 08:36:33 taken-departure dockerd[907]: time="2023-06-08T08:36:33.371274574-03:00" level=info msg="[core] Channel Connectivity change to READY" module=grpc
Jun 08 08:36:33 taken-departure dockerd[907]: time="2023-06-08T08:36:33.373921269-03:00" level=info msg="[core] parsed scheme: \"\"" module=grpc
Jun 08 08:36:33 taken-departure dockerd[907]: time="2023-06-08T08:36:33.373953833-03:00" level=info msg="[core] scheme \"\" not registered, fallback to default scheme" module=grpc
Jun 08 08:36:33 taken-departure dockerd[907]: time="2023-06-08T08:36:33.374057448-03:00" level=info msg="[core] ccResolverWrapper: sending update to cc: {[{192.168.0.138:2377  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
Jun 08 08:36:33 taken-departure dockerd[907]: time="2023-06-08T08:36:33.374075375-03:00" level=info msg="[core] ClientConn switching balancer to \"pick_first\"" module=grpc
Jun 08 08:36:33 taken-departure dockerd[907]: time="2023-06-08T08:36:33.374087612-03:00" level=info msg="[core] Channel switches to new LB policy \"pick_first\"" module=grpc
Jun 08 08:36:33 taken-departure dockerd[907]: time="2023-06-08T08:36:33.374137882-03:00" level=info msg="[core] Subchannel Connectivity change to CONNECTING" module=grpc
Jun 08 08:36:33 taken-departure dockerd[907]: time="2023-06-08T08:36:33.374176497-03:00" level=info msg="manager selected by agent for new session: {0e3qrqn1hrskau5qzzm3c6c5j 192.168.0.138:2377}" module=node/agent node.id=0e3qrqn1hrskau5qzzm3c6c5j
Jun 08 08:36:33 taken-departure dockerd[907]: time="2023-06-08T08:36:33.374244139-03:00" level=info msg="[core] Subchannel picks a new address \"192.168.0.138:2377\" to connect" module=grpc
Jun 08 08:36:33 taken-departure dockerd[907]: time="2023-06-08T08:36:33.374352953-03:00" level=info msg="waiting 0s before registering session" module=node/agent node.id=0e3qrqn1hrskau5qzzm3c6c5j
Jun 08 08:36:33 taken-departure dockerd[907]: time="2023-06-08T08:36:33.374246587-03:00" level=info msg="[core] Channel Connectivity change to CONNECTING" module=grpc
Jun 08 08:36:33 taken-departure dockerd[907]: time="2023-06-08T08:36:33.509202520-03:00" level=info msg="4d0c1af83e637d9b became follower at term 9" module=raft node.id=0e3qrqn1hrskau5qzzm3c6c5j
Jun 08 08:36:33 taken-departure dockerd[907]: time="2023-06-08T08:36:33.509267933-03:00" level=info msg="newRaft 4d0c1af83e637d9b [peers: [4d0c1af83e637d9b], term: 9, commit: 13150, applied: 10000, lastindex: 13150, lastterm: 9]" module=raft node.id=0e3qrqn1hrskau5qzzm3c6c5j
Jun 08 08:36:33 taken-departure dockerd[907]: time="2023-06-08T08:36:33.993769994-03:00" level=info msg="4d0c1af83e637d9b is starting a new election at term 9" module=raft node.id=0e3qrqn1hrskau5qzzm3c6c5j
Jun 08 08:36:33 taken-departure dockerd[907]: time="2023-06-08T08:36:33.993845875-03:00" level=info msg="4d0c1af83e637d9b became candidate at term 10" module=raft node.id=0e3qrqn1hrskau5qzzm3c6c5j
Jun 08 08:36:33 taken-departure dockerd[907]: time="2023-06-08T08:36:33.993872875-03:00" level=info msg="4d0c1af83e637d9b received MsgVoteResp from 4d0c1af83e637d9b at term 10" module=raft node.id=0e3qrqn1hrskau5qzzm3c6c5j
Jun 08 08:36:33 taken-departure dockerd[907]: time="2023-06-08T08:36:33.993902211-03:00" level=info msg="4d0c1af83e637d9b became leader at term 10" module=raft node.id=0e3qrqn1hrskau5qzzm3c6c5j
Jun 08 08:36:33 taken-departure dockerd[907]: time="2023-06-08T08:36:33.993917568-03:00" level=info msg="raft.node: 4d0c1af83e637d9b elected leader 4d0c1af83e637d9b at term 10" module=raft node.id=0e3qrqn1hrskau5qzzm3c6c5j
Jun 08 08:36:33 taken-departure dockerd[907]: time="2023-06-08T08:36:33.997031457-03:00" level=error msg="error creating cluster object" error="name conflicts with an existing object" module=node node.id=0e3qrqn1hrskau5qzzm3c6c5j
Jun 08 08:36:33 taken-departure dockerd[907]: time="2023-06-08T08:36:33.997160205-03:00" level=info msg="leadership changed from not yet part of a raft cluster to 0e3qrqn1hrskau5qzzm3c6c5j" module=node node.id=0e3qrqn1hrskau5qzzm3c6c5j
Jun 08 08:36:33 taken-departure dockerd[907]: time="2023-06-08T08:36:33.997421959-03:00" level=info msg="dispatcher starting" module=dispatcher node.id=0e3qrqn1hrskau5qzzm3c6c5j
Jun 08 08:36:36 taken-departure dockerd[907]: time="2023-06-08T08:36:36.380937716-03:00" level=warning msg="[core] grpc: addrConn.createTransport failed to connect to {192.168.0.138:2377 192.168.0.138:2377 <nil> 0 <nil>}. Err: connection error: desc = \"transport: Error while dialing dial tcp 192.168.0.138:2377: connect: no route to host\". Reconnecting..." module=grpc
Jun 08 08:36:36 taken-departure dockerd[907]: time="2023-06-08T08:36:36.381029052-03:00" level=info msg="[core] Subchannel Connectivity change to TRANSIENT_FAILURE" module=grpc
Jun 08 08:36:36 taken-departure dockerd[907]: time="2023-06-08T08:36:36.381103158-03:00" level=info msg="[core] Channel Connectivity change to TRANSIENT_FAILURE" module=grpc
Jun 08 08:36:36 taken-departure dockerd[907]: time="2023-06-08T08:36:36.381331375-03:00" level=error msg="agent: session failed" backoff=100ms error="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 192.168.0.138:2377: connect: no route to host\"" module=node/agent node.id=0e3qrqn1hrskau5qzzm3c6c5j
Jun 08 08:36:36 taken-departure dockerd[907]: time="2023-06-08T08:36:36.381473148-03:00" level=info msg="[core] Channel Connectivity change to SHUTDOWN" module=grpc
Jun 08 08:36:36 taken-departure dockerd[907]: time="2023-06-08T08:36:36.381515315-03:00" level=info msg="[core] Subchannel Connectivity change to SHUTDOWN" module=grpc
Jun 08 08:36:36 taken-departure dockerd[907]: time="2023-06-08T08:36:36.381573690-03:00" level=info msg="manager selected by agent for new session: { }" module=node/agent node.id=0e3qrqn1hrskau5qzzm3c6c5j
Jun 08 08:36:36 taken-departure dockerd[907]: time="2023-06-08T08:36:36.381644569-03:00" level=info msg="waiting 55.795672ms before registering session" module=node/agent node.id=0e3qrqn1hrskau5qzzm3c6c5j
Jun 08 08:36:36 taken-departure dockerd[907]: time="2023-06-08T08:36:36.525252233-03:00" level=info msg="worker 0e3qrqn1hrskau5qzzm3c6c5j was successfully registered" method="(*Dispatcher).register"
Jun 08 08:36:36 taken-departure dockerd[907]: time="2023-06-08T08:36:36.535397894-03:00" level=info msg="initialized VXLAN UDP port to 4789 "
Jun 08 08:36:36 taken-departure dockerd[907]: time="2023-06-08T08:36:36.535545861-03:00" level=info msg="Initializing Libnetwork Agent Listen-Addr=0.0.0.0 Local-addr=192.168.0.138 Adv-addr=192.168.0.138 Data-addr= Remote-addr-list=[] MTU=1500"
Jun 08 08:36:36 taken-departure dockerd[907]: time="2023-06-08T08:36:36.535829937-03:00" level=info msg="New memberlist node - Node:taken-departure will use memberlist nodeID:9cc3f0df9096 with config:&{NodeID:9cc3f0df9096 Hostname:taken-departure BindAddr:0.0.0.0 AdvertiseAddr:192.168.0.138 BindPort:0 Keys:[[132 110 177 168 142 96 140 203 140 35 156 200 176 2 161 82] [93 99 79 91 59 84 82 163 143 174 47 13 53 152 221 161] [85 78 33 178 59 229 187 87 208 252 19 156 81 157 33 245]] PacketBufferSize:1400 reapEntryInterval:1800000000000 reapNetworkInterval:1825000000000 StatsPrintPeriod:5m0s HealthPrintPeriod:1m0s}"
Jun 08 08:36:36 taken-departure dockerd[907]: time="2023-06-08T08:36:36.536511682-03:00" level=info msg="Daemon has completed initialization"
Jun 08 08:36:36 taken-departure dockerd[907]: time="2023-06-08T08:36:36.537172709-03:00" level=error msg="fatal task error" error="No such container: swarm-network-test_ubuntu.1.srrkwx7jpb14op7mxn1jrfzqn" module=node/agent/taskmanager node.id=0e3qrqn1hrskau5qzzm3c6c5j service.id=hl6zv5poo01aw7b8ydfgys7km task.id=srrkwx7jpb14op7mxn1jrfzqn
Jun 08 08:36:36 taken-departure dockerd[907]: time="2023-06-08T08:36:36.537670368-03:00" level=error msg="fatal task error" error="No such container: videos-test_db1.1.zpzrsqc8g78nr4i36wp255jfu" module=node/agent/taskmanager node.id=0e3qrqn1hrskau5qzzm3c6c5j service.id=ry08na4grh7nw0nha39zc78oo task.id=zpzrsqc8g78nr4i36wp255jfu
Jun 08 08:36:36 taken-departure dockerd[907]: time="2023-06-08T08:36:36.538127609-03:00" level=error msg="fatal task error" error="No such container: swarm-network-test_db1.1.tsf3806eabu7ny6yks55dues6" module=node/agent/taskmanager node.id=0e3qrqn1hrskau5qzzm3c6c5j service.id=mdlqhaan0lo0dk642pzqioemq task.id=tsf3806eabu7ny6yks55dues6
Jun 08 08:36:36 taken-departure dockerd[907]: time="2023-06-08T08:36:36.538506089-03:00" level=info msg="Node 9cc3f0df9096/192.168.0.138, joined gossip cluster"
Jun 08 08:36:36 taken-departure dockerd[907]: time="2023-06-08T08:36:36.539692815-03:00" level=info msg="Node 9cc3f0df9096/192.168.0.138, added to nodes list"
Jun 08 08:36:36 taken-departure dockerd[907]: time="2023-06-08T08:36:36.677720277-03:00" level=info msg="initialized VXLAN UDP port to 4789 "
Jun 08 08:36:36 taken-departure dockerd[907]: time="2023-06-08T08:36:36.788139875-03:00" level=info msg="initialized VXLAN UDP port to 4789 "
Jun 08 08:36:37 taken-departure dockerd[907]: time="2023-06-08T08:36:37.025328407-03:00" level=warning msg="failed to deactivate service binding for container videos-test_db1.1.jpbg0t271rg7n21bjp49eegou" error="No such container: videos-test_db1.1.jpbg0t271rg7n21bjp49eegou" module=node/agent node.id=0e3qrqn1hrskau5qzzm3c6c5j
Jun 08 08:36:37 taken-departure systemd[1]: Started docker.service - Docker Application Container Engine.
Jun 08 08:36:37 taken-departure dockerd[907]: time="2023-06-08T08:36:37.305140060-03:00" level=info msg="API listen on /run/docker.sock"
Jun 08 08:36:39 taken-departure dockerd[907]: time="2023-06-08T08:36:39.352555516-03:00" level=warning msg="Error (Unable to complete atomic operation, key modified) deleting object [endpoint n5av8oclstbow34hndt23uadd 46dcd5b8f54ab5545c005cc628869de84804b4f543ccc1f6105fe67a498c0725], retrying...."
Jun 08 08:36:39 taken-departure dockerd[907]: time="2023-06-08T08:36:39.937475150-03:00" level=error msg="Not continuing with pull after error: errors:\ndenied: requested access to the resource is denied\nunauthorized: authentication required\n"
Jun 08 08:36:39 taken-departure dockerd[907]: time="2023-06-08T08:36:39.937556433-03:00" level=info msg="Ignoring extra error returned from registry: unauthorized: authentication required"
Jun 08 08:36:39 taken-departure dockerd[907]: time="2023-06-08T08:36:39.939908922-03:00" level=error msg="Not continuing with pull after error: errors:\ndenied: requested access to the resource is denied\nunauthorized: authentication required\n"
Jun 08 08:36:39 taken-departure dockerd[907]: time="2023-06-08T08:36:39.940013093-03:00" level=info msg="Ignoring extra error returned from registry: unauthorized: authentication required"
Jun 08 08:36:39 taken-departure dockerd[907]: time="2023-06-08T08:36:39.948571502-03:00" level=error msg="pulling image failed" error="pull access denied for db, repository does not exist or may require 'docker login': denied: requested access to the resource is denied" module=node/agent/taskmanager node.id=0e3qrqn1hrskau5qzzm3c6c5j service.id=ry08na4grh7nw0nha39zc78oo task.id=jne08k586lr3totw0nviqe74l
Jun 08 08:36:39 taken-departure dockerd[907]: time="2023-06-08T08:36:39.955535684-03:00" level=error msg="pulling image failed" error="pull access denied for db, repository does not exist or may require 'docker login': denied: requested access to the resource is denied" module=node/agent/taskmanager node.id=0e3qrqn1hrskau5qzzm3c6c5j service.id=mdlqhaan0lo0dk642pzqioemq task.id=x7otslmb4nutt6ssp66qyzq3t
Jun 08 08:36:47 taken-departure dockerd[907]: time="2023-06-08T08:36:47.363732736-03:00" level=warning msg="deleteServiceInfoFromCluster NetworkDB DeleteEntry failed for abdb52f3113d92f33de8994b6dd12d091449930e04736d5a5af1a4a882f736d3 i13b5hk5q2lqrpjfaptnuwz8o err:cannot delete entry endpoint_table with network id i13b5hk5q2lqrpjfaptnuwz8o and key abdb52f3113d92f33de8994b6dd12d091449930e04736d5a5af1a4a882f736d3 does not exist or is already being deleted"
Jun 08 08:36:47 taken-departure dockerd[907]: time="2023-06-08T08:36:47.363772111-03:00" level=warning msg="rmServiceBinding deleteServiceInfoFromCluster videos-test_db1 abdb52f3113d92f33de8994b6dd12d091449930e04736d5a5af1a4a882f736d3 aborted c.serviceBindings[skey] !ok"
Jun 08 08:36:47 taken-departure dockerd[907]: time="2023-06-08T08:36:47.671660744-03:00" level=error msg="c9e5234c18c8bec53706d1f3ecd64f73dd0f3a1f2801b6dd2b1af544da21581e cleanup: failed to delete container from containerd: no such container"
Jun 08 08:41:36 taken-departure dockerd[907]: time="2023-06-08T08:41:36.539910984-03:00" level=info msg="NetworkDB stats taken-departure(9cc3f0df9096) - netID:n5av8oclstbow34hndt23uadd leaving:false netPeers:1 entries:4 Queue qLen:0 netMsg/s:0"
Jun 08 08:41:36 taken-departure dockerd[907]: time="2023-06-08T08:41:36.540037020-03:00" level=info msg="NetworkDB stats taken-departure(9cc3f0df9096) - netID:mejx1b5gjbp6j6r9b7kbzh6ee leaving:false netPeers:1 entries:5 Queue qLen:0 netMsg/s:0"
Jun 08 08:41:36 taken-departure dockerd[907]: time="2023-06-08T08:41:36.540074962-03:00" level=info msg="NetworkDB stats taken-departure(9cc3f0df9096) - netID:i13b5hk5q2lqrpjfaptnuwz8o leaving:false netPeers:1 entries:9 Queue qLen:0 netMsg/s:0"

...
```

Here are the relevant parts of this log:
```
...

Jun 08 08:36:36 taken-departure dockerd[907]: time="2023-06-08T08:36:36.537172709-03:00" level=error msg="fatal task error" error="No such container: swarm-network-test_ubuntu.1.srrkwx7jpb14op7mxn1jrfzqn" module=node/agent/taskmanager node.id=0e3qrqn1hrskau5qzzm3c6c5j service.id=hl6zv5poo01aw7b8ydfgys7km task.id=srrkwx7jpb14op7mxn1jrfzqn
Jun 08 08:36:36 taken-departure dockerd[907]: time="2023-06-08T08:36:36.537670368-03:00" level=error msg="fatal task error" error="No such container: videos-test_db1.1.zpzrsqc8g78nr4i36wp255jfu" module=node/agent/taskmanager node.id=0e3qrqn1hrskau5qzzm3c6c5j service.id=ry08na4grh7nw0nha39zc78oo task.id=zpzrsqc8g78nr4i36wp255jfu
Jun 08 08:36:36 taken-departure dockerd[907]: time="2023-06-08T08:36:36.538127609-03:00" level=error msg="fatal task error" error="No such container: swarm-network-test_db1.1.tsf3806eabu7ny6yks55dues6" module=node/agent/taskmanager node.id=0e3qrqn1hrskau5qzzm3c6c5j service.id=mdlqhaan0lo0dk642pzqioemq task.id=tsf3806eabu7ny6yks55dues6

...

Jun 08 08:36:39 taken-departure dockerd[907]: time="2023-06-08T08:36:39.937475150-03:00" level=error msg="Not continuing with pull after error: errors:\ndenied: requested access to the resource is denied\nunauthorized: authentication required\n"
Jun 08 08:36:39 taken-departure dockerd[907]: time="2023-06-08T08:36:39.937556433-03:00" level=info msg="Ignoring extra error returned from registry: unauthorized: authentication required"
Jun 08 08:36:39 taken-departure dockerd[907]: time="2023-06-08T08:36:39.939908922-03:00" level=error msg="Not continuing with pull after error: errors:\ndenied: requested access to the resource is denied\nunauthorized: authentication required\n"
Jun 08 08:36:39 taken-departure dockerd[907]: time="2023-06-08T08:36:39.940013093-03:00" level=info msg="Ignoring extra error returned from registry: unauthorized: authentication required"
Jun 08 08:36:39 taken-departure dockerd[907]: time="2023-06-08T08:36:39.948571502-03:00" level=error msg="pulling image failed" error="pull access denied for db, repository does not exist or may require 'docker login': denied: requested access to the resource is denied" module=node/agent/taskmanager node.id=0e3qrqn1hrskau5qzzm3c6c5j service.id=ry08na4grh7nw0nha39zc78oo task.id=jne08k586lr3totw0nviqe74l
Jun 08 08:36:39 taken-departure dockerd[907]: time="2023-06-08T08:36:39.955535684-03:00" level=error msg="pulling image failed" error="pull access denied for db, repository does not exist or may require 'docker login': denied: requested access to the resource is denied" module=node/agent/taskmanager node.id=0e3qrqn1hrskau5qzzm3c6c5j service.id=mdlqhaan0lo0dk642pzqioemq task.id=x7otslmb4nutt6ssp66qyzq3t

...

Jun 08 08:36:47 taken-departure dockerd[907]: time="2023-06-08T08:36:47.671660744-03:00" level=error msg="c9e5234c18c8bec53706d1f3ecd64f73dd0f3a1f2801b6dd2b1af544da21581e cleanup: failed to delete container from containerd: no such container"

...
```

Docker wants to pull the image from a registry instead of respecting the pull policy, which is part of the compose-specification. Of course, I could create a local registry, but if I did that I wouldn't need `deployx` anyway.

I don't know how to reproduce it **exactly**, because when I started testing this deployments, `docker stack` was pulling from local just fine, it was after a couple of reboots and a lot of rebuilds that it started trying to pull from a registry, but after it did, the logs are basically the same, except for the container names, node ids, etc.

I already tried to login using `docker login`, which is something the error messages said to do when pulling with an error with `docker stack`.

Some people suggested adding `DOCKER_BUILDKIT=0` to the environment variables, but then, to make work everytime, I would have to add it in my `/etc/profile` or find a way to add only for docker forever.

It seems that the only fix to this is hosting a local registry.

**Comment by aaraney** [comment] 2023-06-08 14:07
@marcosdly, thanks for reporting this. Just so that we are on the same page, the issue is that `deployx` is not respecting the pull policy as you have it defined in your `compose.yaml` file?

**Comment by marcosdly** [comment] 2023-06-08 14:16
@aaraney I knew that I was forgetting something. I am so sorry.

Here's my compose files. There are separate files for build and deployment so I can build for development and deploy for production without needing to change it manually every time.

### `docker-compose.yml`
```
version: "3.8"

# TODO define dns for comunication between services

# Must be called docker-compose.yml or
# else the build command will not find it.
# There is an option to specify files, but
# the shell completion doesn't work. Annoying.

services:
  db:
    image: db:dev
    container_name: db1-production
    build:
      context: ./db
      target: prod # "prod" or "dev"
      platforms:
        - linux/amd64
      args:
        arch: amd64
        dbport: 5000
```

### `docker-cloud.yml`
```
version: "3.8"

services:
  db1:
    image: db:dev
    pull_policy: never
    tty: true
    stdin_open: true
    read_only: false
    hostname: db-videos-cluster1
    ports:
      # host:container
      - "5005:5000"
    secrets:
      - db-root-username
      - db-root-passwd
    env_file: ./db/.env
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 10s
        window: 15s

  ubuntu:
    image: ubuntu:jammy
    hostname: network-testing
    ports:
      - "5006:5000"
    tty: true
    stdin_open: true
    read_only: false

secrets:
  db-root-username:
    external: true
  db-root-passwd:
    external: true
```

EDIT: `db:dev` is working fine. I'm waiting until the REST-API's first version to be working before bumping it to `db:0.0.1`.

EDIT:
### `./db/Dockerfile`
(Maybe that's relevant?)
```
# syntax=docker/dockerfile:1

ARG arch
ARG dbport

FROM --platform=${arch} mongo:6.0.6-jammy AS prod
COPY --chown=mongodb:mongodb ./scripts /data/scripts
COPY --chown=mongodb:mongodb ./config/mongod.conf /etc/mongod.conf
EXPOSE ${dbport}
```

**Comment by aaraney** [comment] 2023-06-08 15:10
@marcosdly, no worries! I was able to reproduce the issue using the following: 

```yaml
services:
  nginx:
    image: nginx
    pull_policy: never
```

`nginx` is pulled even with the `pull_policy` of `never`. I will look at this more closely this afternoon. My initial reactions is that `Compose V1` never  not supported `pull_policy`, so I am not _overly_ surprised that this is not working at the moment. At the moment, `deployx` only supports the subset of `Compose V2` features that are also present in `Compose V1`. Unfortunately this is a feature outside of that subset. Ill have a look to see if it is possible to support `pull_policy`, however I may be limited by `swarm`'s  api.

**Comment by aaraney** [comment] 2023-06-08 21:40
@marcosdly, after a little digging this _is_ a limitation of the swarm api. Specifically, the `ServiceAPIClient` interface's [`ServiceCreate` method](https://github.com/moby/moby/blob/659604f9ee60f147020bdd444b26e4b5c636dc28/client/interface.go#L143). There is not a way to signal if images should be pulled or not. 

It looks like other have had this question on [stackoverflow](https://stackoverflow.com/a/69081164). If your deployment allows it, it seems the best advice is to pre-pull, or in your case build, images using `docker compose` and then deploy using `deployx`. Otherwise, I think running your own registry is probably your best bet.

This does feel like a bug in the context of `deployx`. I will look into putting in a fix to halt service deployment if the `pull_policy` is `never` and the image is not present. I will need to do a little investing first though.

**Comment by marcosdly** [comment] 2023-06-09 15:57
It's good to have some explanation coming from a developer, regardless. I've been googling, running docker commands, and changing the yaml file arbitrarily trying to circumvent this for some days now (I'm a complete noob).

Yesterday I spent the holiday migrating to k8s. I would have to do it anyway any time soon, might as well.

I appreciate your work, man, thank you.

@aaraney

**Comment by aaraney** [comment] 2023-06-09 17:28
@marcosdly, sorry moving to k8 was the only reasonable way forward, but im glad you got it sorted. Cheers!

**Closed as completed by aaraney** 2023-06-09 17:28 UTC
